### ISSUE TITLE
error in panorama - cannot create clusters_data directory

### ISSUE THREAD

**Issue by CNicholasMDA** [ParkerICI/panorama#1]
HI Federico, I was using panorama and got this error.

Warning: Error in panorama:::plot_clusters: clusters_data directory is missing, data cannot be plotted

Where precisely does the clusters_data directory belong?  in parallel with the clustered directory, or within it?  Or somewhere else?
I was using the GUI for grappolo, vite, and panorama, in MacOS.

**Comment by pfgherardini** [comment]
The `clusters_data` directory should be a subfolder of the folder that contains the graphml files. It should be created automatically when you create the graph though. Is it not there? How are you creating the graph?

**Comment by CNicholasMDA** [comment]
Hi Federico!  Sorry for leaving the old query open.  I don't think I'm having this problem anymore, but if I do I will re-open.  Thanks!
