### ISSUE TITLE
graphics adjustments in heatmaps

### ISSUE THREAD

**Issue by CNicholasMDA** [ParkerICI/panorama#2]
Hi,
when generating the heatmap of communities in the second window, in panorama, I noticed that the lower edge (where the marker names are written) gets cut off and one cannot scroll down any farther to see them.  Is there a way to adjust this in the code? This might be another PC-> Mac complication.
Thanks!
Will post a photo of bug shortly...

![screen shot 2018-09-24 at 4 20 59 pm 2](https://user-images.githubusercontent.com/39345317/46098216-87556100-c189-11e8-9cb7-4be5ac984f12.png)

**Comment by pfgherardini** [comment]
Unfortunately this is  a problem with the R function that generates the heatmap which is not that trivial to fix. I'll add it to the list of improvements

**Comment by CNicholasMDA** [comment]
Ok!  That's cool.  Not a problem.  Thanks Federico!
