### ISSUE TITLE
difficulty de-selecting nodes in panorama

### ISSUE THREAD

**Issue by CNicholasMDA** [ParkerICI/panorama#3]
last one, i promise...
when using Shift+click or Alt+click to select or deselect nodes in panorama, I have noticed that sometimes the node will refuse to be de-selected, and other times the program has developed a "memory", and will ignore my de-selection command when making heat maps or box plots.  any ideas on how to fix?  This is in a MacOS environment, High Sierra 10.13.  I can post more details if necessary.

**Comment by pfgherardini** [comment]
I am not sure I understand. If you alt+click on a blank region of the graph, then it should clear the current selection. Can you give me an exact way to reproduce the problem?

**Comment by CNicholasMDA** [comment]
I remember you teaching us that, but it only works ~50% of the time, and sometimes even when a node is "deselected" (not red anymore) it still gets included in the downstream bar graph, etc. Let me set up the scenario again and I can try to help you reproduce the problem.  It's not a problem that's "on fire" at the moment, so no major worries.

**Comment by CNicholasMDA** [comment]
Hi Federico.  Update: the problem seems to have corrected itself.  alt-clicking to select and deselect nodes now works just fine.  Thanks!
