### ISSUE TITLE
panorama. subscript out of bounds

### ISSUE THREAD

**Issue by algebio** [ParkerICI/panorama#4]
Hi

I can't find where my mistake is. I have repeated every step of the flow-analysis-tutorial with no problem until I try to run panorama::panorama() on either my ubuntu terminal or RStudio.

In RStudio I get this message:

Warning: Error in [[: subscript out of bounds
  48: getSliderType
  47: updateSliderInput
  46: <observer> [/home/juan/R/x86_64-pc-linux-gnu-library/3.4/panorama/shinyGUI/server/tab_graph.R#315]
   3: <Anonymous>
   1: panorama::panorama

Any clue is much appreciate.

Cheers
Juan

**Comment by algebio** [comment]
This is the complete message from RStudio:

> panorama::panorama()

Listening on http://127.0.0.1:8072
14: .Call("_later_execCallbacks", PACKAGE = "later", timeoutSecs)
13: execCallbacks(timeoutSecs)
12: run_now(timeoutMs/1000)
11: service(timeout)
10: serviceApp()
9: ..stacktracefloor..(serviceApp())
8: withCallingHandlers(expr, error = doCaptureStack)
7: globals$domain$wrapSync(expr)
6: promises::with_promise_domain(createStackTracePromiseDomain(), 
       expr)
5: captureStackTraces({
       while (!.globals$stopped) {
           ..stacktracefloor..(serviceApp())
           Sys.sleep(0.001)
       }
   })
4: ..stacktraceoff..(captureStackTraces({
       while (!.globals$stopped) {
           ..stacktracefloor..(serviceApp())
           Sys.sleep(0.001)
       }
   }))
3: (function (appDir = getwd(), port = getOption("shiny.port"), 
       launch.browser = getOption("shiny.launch.browser", interactive()), 
       host = getOption("shiny.host", "127.0.0.1"), workerId = "", 
       quiet = FALSE, display.mode = c("auto", "normal", "showcase"), 
       test.mode = getOption("shiny.testmode", FALSE)) 
   {
       on.exit({
           handlerManager$clear()
       }, add = TRUE)
       if (.globals$running) {
           stop("Can't call `runApp()` from within `runApp()`. If your ", 
               "application code contains `runApp()`, please remove it.")
       }
       .globals$running <- TRUE
       on.exit({
           .globals$running <- FALSE
       }, add = TRUE)
       oldOptionSet <- .globals$options
       on.exit({
           .globals$options <- oldOptionSet
       }, add = TRUE)
       shinyOptions(appToken = createUniqueId(8))
       ops <- options(warn = max(1, getOption("warn", default = 1)), 
           pool.scheduler = scheduleTask)
       on.exit(options(ops), add = TRUE)
       if (is.null(getShinyOption("cache"))) {
           shinyOptions(cache = MemoryCache$new())
       }
       appParts <- as.shiny.appobj(appDir)
       appOps <- appParts$options
       findVal <- function(arg, default) {
           if (arg %in% names(appOps)) 
               appOps[[arg]]
           else default
       }
       if (missing(port)) 
           port <- findVal("port", port)
       if (missing(launch.browser)) 
           launch.browser <- findVal("launch.browser", launch.browser)
       if (missing(host)) 
           host <- findVal("host", host)
       if (missing(quiet)) 
           quiet <- findVal("quiet", quiet)
       if (missing(display.mode)) 
           display.mode <- findVal("display.mode", display.mode)
       if (missing(test.mode)) 
           test.mode <- findVal("test.mode", test.mode)
       if (is.null(host) || is.na(host)) 
           host <- "0.0.0.0"
       workerId(workerId)
       if (inShinyServer()) {
           ver <- Sys.getenv("SHINY_SERVER_VERSION")
           if (utils::compareVersion(ver, .shinyServerMinVersion) < 
               0) {
               warning("Shiny Server v", .shinyServerMinVersion, 
                   " or later is required; please upgrade!")
           }
       }
       setShowcaseDefault(0)
       .globals$testMode <- test.mode
       if (test.mode) {
           message("Running application in test mode.")
       }
       if (is.character(appDir)) {
           desc <- file.path.ci(if (tolower(tools::file_ext(appDir)) == 
               "r") 
               dirname(appDir)
           else appDir, "DESCRIPTION")
           if (file.exists(desc)) {
               con <- file(desc, encoding = checkEncoding(desc))
               on.exit(close(con), add = TRUE)
               settings <- read.dcf(con)
               if ("DisplayMode" %in% colnames(settings)) {
                   mode <- settings[1, "DisplayMode"]
                   if (mode == "Showcase") {
                     setShowcaseDefault(1)
                     if ("IncludeWWW" %in% colnames(settings)) {
                       .globals$IncludeWWW <- as.logical(settings[1, 
                         "IncludeWWW"])
                       if (is.na(.globals$IncludeWWW)) {
                         stop("In your Description file, `IncludeWWW` ", 
                           "must be set to `True` (default) or `False`")
                       }
                     }
                     else {
                       .globals$IncludeWWW <- TRUE
                     }
                   }
               }
           }
       }
       if (is.null(.globals$IncludeWWW) || is.na(.globals$IncludeWWW)) {
           .globals$IncludeWWW <- TRUE
       }
       display.mode <- match.arg(display.mode)
       if (display.mode == "normal") {
           setShowcaseDefault(0)
       }
       else if (display.mode == "showcase") {
           setShowcaseDefault(1)
       }
       require(shiny)
       if (is.null(port)) {
           for (i in 1:20) {
               if (!is.null(.globals$lastPort)) {
                   port <- .globals$lastPort
                   .globals$lastPort <- NULL
               }
               else {
                   while (TRUE) {
                     port <- p_randomInt(3000, 8000)
                     if (!port %in% c(3659, 4045, 6000, 6665:6669, 
                       6697)) {
                       break
                     }
                   }
               }
               tmp <- try(startServer(host, port, list()), silent = TRUE)
               if (!inherits(tmp, "try-error")) {
                   stopServer(tmp)
                   .globals$lastPort <- port
                   break
               }
           }
       }
       on.exit({
           .globals$onStopCallbacks$invoke()
           .globals$onStopCallbacks <- Callbacks$new()
       }, add = TRUE)
       unconsumeAppOptions(appParts$appOptions)
       if (!is.null(appParts$onStop)) 
           on.exit(appParts$onStop(), add = TRUE)
       if (!is.null(appParts$onStart)) 
           appParts$onStart()
       server <- startApp(appParts, port, host, quiet)
       on.exit({
           stopServer(server)
       }, add = TRUE)
       if (!is.character(port)) {
           browseHost <- host
           if (identical(host, "0.0.0.0")) {
               browseHost <- "127.0.0.1"
           }
           else if (identical(host, "::")) {
               browseHost <- "::1"
           }
           if (httpuv::ipFamily(browseHost) == 6L) {
               browseHost <- paste0("[", browseHost, "]")
           }
           appUrl <- paste("http://", browseHost, ":", port, sep = "")
           if (is.function(launch.browser)) 
               launch.browser(appUrl)
           else if (launch.browser) 
               utils::browseURL(appUrl)
       }
       else {
           appUrl <- NULL
       }
       callAppHook("onAppStart", appUrl)
       on.exit({
           callAppHook("onAppStop", appUrl)
       }, add = TRUE)
       .globals$reterror <- NULL
       .globals$retval <- NULL
       .globals$stopped <- FALSE
       ..stacktraceoff..(captureStackTraces({
           while (!.globals$stopped) {
               ..stacktracefloor..(serviceApp())
               Sys.sleep(0.001)
           }
       }))
       if (isTRUE(.globals$reterror)) {
           stop(.globals$retval)
       }
       else if (.globals$retval$visible) 
           .globals$retval$value
       else invisible(.globals$retval$value)
   })(port = 8072, appDir = "/home/juan/R/x86_64-pc-linux-gnu-library/3.4/panorama/shinyGUI", 
       launch.browser = TRUE)
2: do.call(shiny::runApp, args)
1: panorama::panorama()
Warning: Error in [[: subscript out of bounds
  48: getSliderType
  47: updateSliderInput
  46: <observer> [/home/juan/R/x86_64-pc-linux-gnu-library/3.4/panorama/shinyGUI/server/tab_graph.R#315]
   3: <Anonymous>
   1: panorama::panorama

**Comment by algebio** [comment]
version:

platform    x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          4.0                         
year           2017                        
month          04                          
day            21                          
svn rev        72570                       
language       R                           
version.string R version 3.4.0 (2017-04-21)
nickname       You Stupid Darkness

**Comment by pfgherardini** [comment]
Hi,

Is the error right when you launch the software? Or after you try to do a specific operation? Can you describe exactly what you are doing?

Thanks

Federico

**Comment by algebio** [comment]
Hi Federico

I've created several graphml files using vite and the sample data provided with the flow-analysis-tutorial. Then I type panorama::panorama() on RStudio and immediately I can see a new panorama tab on my browser and a new window pop up to select the graphml file. So far, so good. Then I choose the folder "unsupervised_graph" to select "blood_unsupervised.graphml" or the folder "scaffold_result" to select any of the .graphml there (all.pooled, BLD.pooled, BM.pooled, etc). Rstudio shows the same error message after opening any of those graphml files. 

Warning: Error in [[: subscript out of bounds
  48: getSliderType
  47: updateSliderInput
  46: <observer> [/home/juan/R/x86_64-pc-linux-gnu-library/3.4/panorama/shinyGUI/server/tab_graph.R#315]
   3: <Anonymous>
   1: panorama::panorama

I'm using RStudio on the server of the lab where I keep the ParkerICI sample data.

I hope I gave you some useful information. Please, don't hesitate to ask if I forgot something, I'm quite new to bioinf. 

Regards
Juan

**Comment by pfgherardini** [comment]
Can you start a new R session and post the results of running the following commands?

```
library(panorama)
sessionInfo()
```

**Comment by algebio** [comment]
Hi Federico

I started a new session and this is what I got:

R version 3.4.0 (2017-04-21) -- "You Stupid Darkness"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Workspace loaded from ~/.RData]

Loading required package: flowCore

Attaching package: ‘flowCore’

The following object is masked from ‘package:base’:

    sort

> library(panorama)
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.18.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
[1] panorama_0.1.0  flowCore_1.44.2

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0          lattice_0.20-35    
 [3] matrixStats_0.54.0  mvtnorm_1.0-8      
 [5] corpcor_1.6.9       rrcov_1.4-4        
 [7] grid_3.4.0          magrittr_1.5       
 [9] stats4_3.4.0        pcaPP_1.9-73       
[11] graph_1.56.0        robustbase_0.93-3  
[13] tools_3.4.0         Biobase_2.38.0     
[15] igraph_1.2.2        DEoptimR_1.0-8     
[17] parallel_3.4.0      compiler_3.4.0     
[19] pkgconfig_2.0.2     BiocGenerics_0.24.0
[21] cluster_2.0.6

**Comment by pfgherardini** [comment]
That's missing info about the shiny version.... my bad.

Can you write the following

```
library(shiny)
sessionInfo()
```

**Comment by algebio** [comment]
Hi Federico
Thanks for your help

> library(shiny)
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.18.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8    LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.2.0     premessa_0.2.3  panorama_0.1.0  flowCore_1.44.2

loaded via a namespace (and not attached):
 [1] igraph_1.2.2        graph_1.56.0        Rcpp_1.0.0          cluster_2.0.6       magrittr_1.5        BiocGenerics_0.24.0
 [7] xtable_1.8-3        lattice_0.20-35     R6_2.3.0            rrcov_1.4-4         pcaPP_1.9-73        tools_3.4.0        
[13] parallel_3.4.0      grid_3.4.0          Biobase_2.38.0      corpcor_1.6.9       htmltools_0.3.6     matrixStats_0.54.0 
[19] digest_0.6.18       later_0.7.5         promises_1.0.1      mime_0.6            robustbase_0.93-3   compiler_3.4.0     
[25] DEoptimR_1.0-8      stats4_3.4.0        mvtnorm_1.0-8       httpuv_1.4.5        pkgconfig_2.0.2

**Comment by pfgherardini** [comment]
Ok I was able to reproduce this. This is related to the newest version of the shiny package. Let me investigate, I should have a fix soon

**Comment by pfgherardini** [comment]
Fixed in the latest release, thank you very much for reporting

**Comment by algebio** [comment]
Hi Federico

It works fine now. Great job. Thanks for your help.

Juan.
