### ISSUE TITLE
panorama: save plots

### ISSUE THREAD

**Issue by Terskikh** [ParkerICI/panorama#5]
Dear Pier,
I started to use Scaffold not long time ago. I have an issue to save/export created plot in package panorama(). Is it any smart way to do when I run analysis using GUI version? Or shall I run the script from R environment?
Thank you in advance for your reply!

**Comment by pfgherardini** [comment]
Hi,

Unfortunately not at the moment. The only way is to take a screenshot of the browser window. Sorry for the inconvenience.

Federico
